### ISSUE TITLE
自己摸着良心问问，作弊抓你有问题？

### ISSUE THREAD

**Issue by ghost** [chengyumeng/chujianfeng#4]
作弊被抓，心里没点笔数？
无情不代表什么。

**Comment by ghost** [comment]
不代表任何言论，只是你这种抓出来一个人批斗的方式，和某D有什么区别？

**Comment by asuna0512** [comment]
真是辛苦@adsjfoasdoi 同学为了洗白chu，抹黑自己同学，而特地注册一个github账号了~

**Comment by ghost** [comment]
可以的，说个事实就是洗白。杠精？

**Comment by ghost** [comment]
我不会把我的大号用在这种~~无聊~~智障project上。

**Comment by ghost** [comment]
我自己都是作弊被他抓过的人，我没有觉得他抓我有任何问题。
错了就是错了，只是被抓的都不敢承认自己的错误而已。

**Comment by asuna0512** [comment]
@adsjfoasdoi 兄台。。你自己作弊了就是自己作弊了。。不要拉着别的同学，诬陷说别人也作弊了好么。。你可能都没有仔细看 @chengyumeng 同学上传的各种文件内容吧。。等你仔细看完了再提issues

**Comment by chengyumeng** [comment]
@adsjfoasdoi 请仔细参阅本项目相关内容再提 issue ，请不要使用脏话，祝好。

**Comment by ghost** [comment]
@asuna0512 考试手册没有看？没签过字？桌面文字问题没有条例么？按规则规矩来，这不是他的错。你可以建议提交PR去把考试手册改掉。

**Comment by ghost** [comment]
建议去修改考试说明系列规定。
